# python of course and we don't need access to sudo atm
language: python
sudo: false

# emails are annoying
notifications:
    email: false

# build on Ubuntu 14.04 because the default is
# really old
os: linux
dist: trusty

# test on the latest version of python
#python:
 #   - "3.7"

# only run travis on the master branch
branches:
    only:
        - master

# install dependencies listed in requirements
#install: "pip install -r requirements.txt"

# New dependencies from other yaml:
install:
  # Source: https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/use-conda-with-travis-ci.html
  # get miniconda to be able to use conda in Travis
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
  
  # actual environment installation
 - conda env create --file windows_environment.yml
 - conda activate tudat-space

# run tests
script:
    "python -m pytest -v test/*"
