# python of course and we don't need access to sudo atm
language: python
sudo: false

# emails are annoying
notifications:
    email: false

# build on Ubuntu 14.04 because the default is
# really old
os: linux
dist: trusty

# test on the latest version of python
#python:
 #   - "3.7"

# only run travis on the master branch
branches:
    only:
        - master

# install dependencies listed in requirements
#install: "pip install -r requirements.txt"

# New dependencies from other yaml:
install:
 - conda env create --file windows_environment.yml
 - conda activate tudat-space

# run tests
script:
    "python -m pytest -v test/*"
