# run: conda env create --file tudat-space_environment.yml
# include new packages: conda env update --file tudat-space_environment.yml
name: tudat-space
channels:
  - conda-forge
  - tudat-team
  - conda
dependencies:
- anaconda
- nb_conda
- conda:
  - pytest>=3.0
  - nbconvert
  - matplotlib
  - ipykernel
  - tudatpy
- pip
- pip:
  # works for regular pip packages
  - pdflatex
  - testbook
  - pyment
  - pdoc3
