# run: conda env create --file linux_environment.yml
# include new packages: conda env update --file linux_environment.yml
name: tudat-space
channels:
  - conda-forge
  - tudat-team
dependencies:
  - tudatpy
  - matplotlib
- conda:
  - pytest>=3.0